name: yuv_ffi_example
description: "Demonstrates how to use the yuv_ffi plugin."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0'


dependencies:
  flutter:
    sdk: flutter

  yuv_ffi:
    path: ../

  cupertino_icons: ^1.0.8
  share_plus: ^11.0.0
  path_provider: ^2.1.5
  material_design_icons_flutter: ^7.0.7296
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  google_mlkit_face_detection: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true