name: yuv_ffi_example
description: "Demonstrates how to use the yuv_ffi plugin."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  yuv_ffi:
    path: ../

  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  flutter_plugin_android_lifecycle: ^2.0.28
  share_plus: ^11.0.0
  path_provider: ^2.1.5
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  ffi:

flutter:
  uses-material-design: true