// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// FFI bindings for native YUV code
class YuvFfiBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  YuvFfiBindings(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  YuvFfiBindings.fromLookup(ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup) : _lookup = lookup;

  int yuv_black_white_v1(ffi.Pointer<YuvConstFrameV1> source, ffi.Pointer<YuvMutableFrameV1> destination, ffi.Pointer<YuvEffectOptionsV1> options) {
    return _yuv_black_white_v1(source, destination, options);
  }

  late final _yuv_black_white_v1Ptr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<YuvConstFrameV1>, ffi.Pointer<YuvMutableFrameV1>, ffi.Pointer<YuvEffectOptionsV1>)>>(
        'yuv_black_white_v1',
      );
  late final _yuv_black_white_v1 = _yuv_black_white_v1Ptr
      .asFunction<int Function(ffi.Pointer<YuvConstFrameV1>, ffi.Pointer<YuvMutableFrameV1>, ffi.Pointer<YuvEffectOptionsV1>)>();

  int yuv_box_blur_v1(ffi.Pointer<YuvConstFrameV1> source, ffi.Pointer<YuvMutableFrameV1> destination, ffi.Pointer<YuvBlurOptionsV1> options) {
    return _yuv_box_blur_v1(source, destination, options);
  }

  late final _yuv_box_blur_v1Ptr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<YuvConstFrameV1>, ffi.Pointer<YuvMutableFrameV1>, ffi.Pointer<YuvBlurOptionsV1>)>>(
        'yuv_box_blur_v1',
      );
  late final _yuv_box_blur_v1 = _yuv_box_blur_v1Ptr
      .asFunction<int Function(ffi.Pointer<YuvConstFrameV1>, ffi.Pointer<YuvMutableFrameV1>, ffi.Pointer<YuvBlurOptionsV1>)>();

  int yuv_chroma_swap_v1(ffi.Pointer<YuvConstFrameV1> source, ffi.Pointer<YuvMutableFrameV1> destination, ffi.Pointer<YuvEffectOptionsV1> options) {
    return _yuv_chroma_swap_v1(source, destination, options);
  }

  late final _yuv_chroma_swap_v1Ptr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<YuvConstFrameV1>, ffi.Pointer<YuvMutableFrameV1>, ffi.Pointer<YuvEffectOptionsV1>)>>(
        'yuv_chroma_swap_v1',
      );
  late final _yuv_chroma_swap_v1 = _yuv_chroma_swap_v1Ptr
      .asFunction<int Function(ffi.Pointer<YuvConstFrameV1>, ffi.Pointer<YuvMutableFrameV1>, ffi.Pointer<YuvEffectOptionsV1>)>();

  int yuv_convert_v1(ffi.Pointer<YuvConstFrameV1> source, ffi.Pointer<YuvMutableFrameV1> destination, ffi.Pointer<YuvConvertOptionsV1> options) {
    return _yuv_convert_v1(source, destination, options);
  }

  late final _yuv_convert_v1Ptr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<YuvConstFrameV1>, ffi.Pointer<YuvMutableFrameV1>, ffi.Pointer<YuvConvertOptionsV1>)>>(
        'yuv_convert_v1',
      );
  late final _yuv_convert_v1 = _yuv_convert_v1Ptr
      .asFunction<int Function(ffi.Pointer<YuvConstFrameV1>, ffi.Pointer<YuvMutableFrameV1>, ffi.Pointer<YuvConvertOptionsV1>)>();

  int yuv_crop_v1(ffi.Pointer<YuvConstFrameV1> source, ffi.Pointer<YuvMutableFrameV1> destination, ffi.Pointer<YuvCropOptionsV1> options) {
    return _yuv_crop_v1(source, destination, options);
  }

  late final _yuv_crop_v1Ptr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<YuvConstFrameV1>, ffi.Pointer<YuvMutableFrameV1>, ffi.Pointer<YuvCropOptionsV1>)>>(
        'yuv_crop_v1',
      );
  late final _yuv_crop_v1 = _yuv_crop_v1Ptr
      .asFunction<int Function(ffi.Pointer<YuvConstFrameV1>, ffi.Pointer<YuvMutableFrameV1>, ffi.Pointer<YuvCropOptionsV1>)>();

  int yuv_flip_v1(ffi.Pointer<YuvConstFrameV1> source, ffi.Pointer<YuvMutableFrameV1> destination, ffi.Pointer<YuvFlipOptionsV1> options) {
    return _yuv_flip_v1(source, destination, options);
  }

  late final _yuv_flip_v1Ptr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<YuvConstFrameV1>, ffi.Pointer<YuvMutableFrameV1>, ffi.Pointer<YuvFlipOptionsV1>)>>(
        'yuv_flip_v1',
      );
  late final _yuv_flip_v1 = _yuv_flip_v1Ptr
      .asFunction<int Function(ffi.Pointer<YuvConstFrameV1>, ffi.Pointer<YuvMutableFrameV1>, ffi.Pointer<YuvFlipOptionsV1>)>();

  int yuv_gaussian_blur_v1(ffi.Pointer<YuvConstFrameV1> source, ffi.Pointer<YuvMutableFrameV1> destination, ffi.Pointer<YuvBlurOptionsV1> options) {
    return _yuv_gaussian_blur_v1(source, destination, options);
  }

  late final _yuv_gaussian_blur_v1Ptr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<YuvConstFrameV1>, ffi.Pointer<YuvMutableFrameV1>, ffi.Pointer<YuvBlurOptionsV1>)>>(
        'yuv_gaussian_blur_v1',
      );
  late final _yuv_gaussian_blur_v1 = _yuv_gaussian_blur_v1Ptr
      .asFunction<int Function(ffi.Pointer<YuvConstFrameV1>, ffi.Pointer<YuvMutableFrameV1>, ffi.Pointer<YuvBlurOptionsV1>)>();

  int yuv_grayscale_v1(ffi.Pointer<YuvConstFrameV1> source, ffi.Pointer<YuvMutableFrameV1> destination, ffi.Pointer<YuvEffectOptionsV1> options) {
    return _yuv_grayscale_v1(source, destination, options);
  }

  late final _yuv_grayscale_v1Ptr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<YuvConstFrameV1>, ffi.Pointer<YuvMutableFrameV1>, ffi.Pointer<YuvEffectOptionsV1>)>>(
        'yuv_grayscale_v1',
      );
  late final _yuv_grayscale_v1 = _yuv_grayscale_v1Ptr
      .asFunction<int Function(ffi.Pointer<YuvConstFrameV1>, ffi.Pointer<YuvMutableFrameV1>, ffi.Pointer<YuvEffectOptionsV1>)>();

  int yuv_mean_blur_v1(ffi.Pointer<YuvConstFrameV1> source, ffi.Pointer<YuvMutableFrameV1> destination, ffi.Pointer<YuvBlurOptionsV1> options) {
    return _yuv_mean_blur_v1(source, destination, options);
  }

  late final _yuv_mean_blur_v1Ptr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<YuvConstFrameV1>, ffi.Pointer<YuvMutableFrameV1>, ffi.Pointer<YuvBlurOptionsV1>)>>(
        'yuv_mean_blur_v1',
      );
  late final _yuv_mean_blur_v1 = _yuv_mean_blur_v1Ptr
      .asFunction<int Function(ffi.Pointer<YuvConstFrameV1>, ffi.Pointer<YuvMutableFrameV1>, ffi.Pointer<YuvBlurOptionsV1>)>();

  int yuv_negate_v1(ffi.Pointer<YuvConstFrameV1> source, ffi.Pointer<YuvMutableFrameV1> destination, ffi.Pointer<YuvEffectOptionsV1> options) {
    return _yuv_negate_v1(source, destination, options);
  }

  late final _yuv_negate_v1Ptr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<YuvConstFrameV1>, ffi.Pointer<YuvMutableFrameV1>, ffi.Pointer<YuvEffectOptionsV1>)>>(
        'yuv_negate_v1',
      );
  late final _yuv_negate_v1 = _yuv_negate_v1Ptr
      .asFunction<int Function(ffi.Pointer<YuvConstFrameV1>, ffi.Pointer<YuvMutableFrameV1>, ffi.Pointer<YuvEffectOptionsV1>)>();

  int yuv_rotate_v1(ffi.Pointer<YuvConstFrameV1> source, ffi.Pointer<YuvMutableFrameV1> destination, ffi.Pointer<YuvRotateOptionsV1> options) {
    return _yuv_rotate_v1(source, destination, options);
  }

  late final _yuv_rotate_v1Ptr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<YuvConstFrameV1>, ffi.Pointer<YuvMutableFrameV1>, ffi.Pointer<YuvRotateOptionsV1>)>>(
        'yuv_rotate_v1',
      );
  late final _yuv_rotate_v1 = _yuv_rotate_v1Ptr
      .asFunction<int Function(ffi.Pointer<YuvConstFrameV1>, ffi.Pointer<YuvMutableFrameV1>, ffi.Pointer<YuvRotateOptionsV1>)>();
}

final class YuvBlurOptionsV1 extends ffi.Struct {
  @ffi.Uint32()
  external int structSize;

  @ffi.Uint32()
  external int abiVersion;

  @ffi.Uint32()
  external int radius;

  @ffi.Uint32()
  external int borderMode;

  @ffi.Double()
  external double sigma;

  external YuvRegionOptionsV1 region;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.Uint64> reserved;
}

final class YuvConstFrameV1 extends ffi.Struct {
  @ffi.Uint32()
  external int structSize;

  @ffi.Uint32()
  external int abiVersion;

  @ffi.Uint32()
  external int format;

  @ffi.Uint32()
  external int planeCount;

  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Uint32()
  external int colorMatrix;

  @ffi.Uint32()
  external int colorRange;

  @ffi.Array.multi([3])
  external ffi.Array<YuvConstPlaneV1> planes;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Uint64> reserved;
}

final class YuvConstPlaneV1 extends ffi.Struct {
  @ffi.Uint64()
  external int length;

  @ffi.Uint64()
  external int rowStride;

  @ffi.Uint32()
  external int pixelStride;

  @ffi.Uint32()
  external int sampleBytes;

  external ffi.Pointer<ffi.Uint8> data;

  static ffi.Pointer<YuvConstPlaneV1> $allocate(
    ffi.Allocator $allocator, {
    required int length,
    required int rowStride,
    required int pixelStride,
    required int sampleBytes,
    required ffi.Pointer<ffi.Uint8> data,
  }) => $allocator<YuvConstPlaneV1>()
    ..ref.length = length
    ..ref.rowStride = rowStride
    ..ref.pixelStride = pixelStride
    ..ref.sampleBytes = sampleBytes
    ..ref.data = data;
}

final class YuvConvertOptionsV1 extends ffi.Struct {
  @ffi.Uint32()
  external int structSize;

  @ffi.Uint32()
  external int abiVersion;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.Uint64> reserved;
}

final class YuvCropOptionsV1 extends ffi.Struct {
  @ffi.Uint32()
  external int structSize;

  @ffi.Uint32()
  external int abiVersion;

  @ffi.Int32()
  external int left;

  @ffi.Int32()
  external int top;

  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Array.multi([1])
  external ffi.Array<ffi.Uint64> reserved;
}

final class YuvEffectOptionsV1 extends ffi.Struct {
  @ffi.Uint32()
  external int structSize;

  @ffi.Uint32()
  external int abiVersion;

  external YuvRegionOptionsV1 region;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.Uint64> reserved;
}

final class YuvFlipOptionsV1 extends ffi.Struct {
  @ffi.Uint32()
  external int structSize;

  @ffi.Uint32()
  external int abiVersion;

  @ffi.Uint32()
  external int direction;

  @ffi.Uint32()
  external int reserved0;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.Uint64> reserved;
}

final class YuvMutableFrameV1 extends ffi.Struct {
  @ffi.Uint32()
  external int structSize;

  @ffi.Uint32()
  external int abiVersion;

  @ffi.Uint32()
  external int format;

  @ffi.Uint32()
  external int planeCount;

  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Uint32()
  external int colorMatrix;

  @ffi.Uint32()
  external int colorRange;

  @ffi.Array.multi([3])
  external ffi.Array<YuvMutablePlaneV1> planes;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Uint64> reserved;
}

final class YuvMutablePlaneV1 extends ffi.Struct {
  @ffi.Uint64()
  external int length;

  @ffi.Uint64()
  external int rowStride;

  @ffi.Uint32()
  external int pixelStride;

  @ffi.Uint32()
  external int sampleBytes;

  external ffi.Pointer<ffi.Uint8> data;

  static ffi.Pointer<YuvMutablePlaneV1> $allocate(
    ffi.Allocator $allocator, {
    required int length,
    required int rowStride,
    required int pixelStride,
    required int sampleBytes,
    required ffi.Pointer<ffi.Uint8> data,
  }) => $allocator<YuvMutablePlaneV1>()
    ..ref.length = length
    ..ref.rowStride = rowStride
    ..ref.pixelStride = pixelStride
    ..ref.sampleBytes = sampleBytes
    ..ref.data = data;
}

final class YuvRegionOptionsV1 extends ffi.Struct {
  @ffi.Uint32()
  external int structSize;

  @ffi.Uint32()
  external int abiVersion;

  @ffi.Int32()
  external int left;

  @ffi.Int32()
  external int top;

  @ffi.Int32()
  external int right;

  @ffi.Int32()
  external int bottom;

  @ffi.Uint32()
  external int enabled;

  @ffi.Uint32()
  external int reserved0;

  static ffi.Pointer<YuvRegionOptionsV1> $allocate(
    ffi.Allocator $allocator, {
    required int structSize,
    required int abiVersion,
    required int left,
    required int top,
    required int right,
    required int bottom,
    required int enabled,
    required int reserved0,
  }) => $allocator<YuvRegionOptionsV1>()
    ..ref.structSize = structSize
    ..ref.abiVersion = abiVersion
    ..ref.left = left
    ..ref.top = top
    ..ref.right = right
    ..ref.bottom = bottom
    ..ref.enabled = enabled
    ..ref.reserved0 = reserved0;
}

final class YuvRotateOptionsV1 extends ffi.Struct {
  @ffi.Uint32()
  external int structSize;

  @ffi.Uint32()
  external int abiVersion;

  @ffi.Uint32()
  external int rotationDegrees;

  @ffi.Uint32()
  external int reserved0;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.Uint64> reserved;
}
