import 'dart:convert';
import 'dart:ffi';
import 'dart:math';

import 'package:ffi/ffi.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

/// BGRA-04, follow-up review requirement: `bgra04_copy_out_candidates_pixel3_test.dart`
/// runs all 30 samples of candidate A, then all 30 of B, then C, then D, in a
/// single block per candidate. The 2026-09-27 follow-up review
/// (`doc/perf/results/bgra_review_2026-09-27_followup.md`, section "BGRA-04:
/// отрицательный вывод пока слишком широк") flagged that block order as a
/// confound: any drift in device thermal/scheduler state over the ~4-6
/// seconds of a 30-sample block could masquerade as a real difference
/// between candidates, particularly since D was faster than A on tight in
/// two prior Android runs.
///
/// This file isolates exactly the comparison the review asked for: candidate
/// **A** (`Uint8List.fromList(ptr.asTypedList(len))`, current production) vs
/// candidate **D** (`ByteBuffer.asUint8List(...).sublist(0)`, the most
/// promising alternative across prior runs) on the **tight 1920x1080**
/// scenario only -- the only scenario that matches `convert()`'s actual
/// destination layout (BGRA-03 established tight-only for `convert()`;
/// padded/ROI are not this card's production-relevant shape). B and C are
/// deliberately dropped here: they were never the closest competitor to A,
/// and narrowing to the one real contender is what buys the sample budget
/// this file spends on randomization/interleaving instead.
///
/// ## Order control: seeded random permutation, not fixed alternation
///
/// A fixed A,D,A,D,... alternation would still let a *periodic* effect (e.g.
/// a scheduler tick or thermal cycle at a period close to one iteration)
/// alias with the labels. Instead, each of the 60 draws (30 A + 30 D) is
/// assigned a uniformly random slot using a fixed seed
/// (`Random(0xB6DA04)`, chosen once, before this file was run against real
/// hardware -- see the pre-registered threshold note below for why the seed
/// itself is not tuned post-hoc: the seed only controls *order*, not the
/// values, so no seed choice can manufacture a result). The permutation is
/// generated by a Fisher-Yates shuffle of 30 A-tags and 30 D-tags, then
/// walked once. Every sample's real candidate label travels with it in the
/// raw order string. The A and D sample arrays keep encounter order, so the
/// full sequence can be reconstructed without emitting a logcat-truncated
/// JSON array of 60 objects.
///
/// ## Pre-registered practical significance threshold: 5%
///
/// Fixed **before** this file was run against the device, in this same
/// commit, per the task's explicit requirement to decide the threshold
/// before seeing results (to rule out post-hoc threshold-fitting).
/// Rationale for 5%, not e.g. 3% or 10%:
/// - BGRA-00's stage breakdown put copy-out at ~7% of the full tight-1080p
///   `toBgraBytes()` call. A candidate that wins by less than 5% on copy-out
///   alone would move the *full call* by well under 1%, which is not worth
///   the risk of touching the buffer-lifetime-sensitive copy-out step for.
/// - Prior block-ordered runs measured D ahead of A on tight by -3.6% to
///   -9%, straddling 5% -- a threshold at exactly that boundary is the
///   correct place to force this interleaved experiment to actually decide
///   the question, rather than picking a threshold so low that ordinary
///   run-to-run jitter would count as a "win", or so high that no bulk-copy
///   API swap could plausibly ever clear it.
/// - 3-5% is within the observed run-to-run median jitter of unrelated BGRA
///   cards on this exact device (BGRA-01/02 Android reruns moved by
///   0.1-1%pt between otherwise-identical sessions); 5% sits at the upper
///   edge of that noise band rather than inside it, so clearing it is a
///   meaningfully stronger claim than "look, a smaller number".
///
/// A result is called a **positive, durable win for D** only if D's median
/// is at least 5% lower than A's median, and this holds consistently (not by
/// a single lucky round) -- see the "Verdict" JSON line this file emits,
/// which computes this automatically from the medians it just measured.
///
/// ## Safety of the "D" substitution (documented regardless of outcome)
///
/// Both A and D operate on a `Pointer<Uint8>` allocated by this file via
/// `package:ffi`'s `malloc`, exactly mirroring how `_copyDestinationPlanes`
/// receives the native destination pointer from `YuvAbiV1Runner._run` (see
/// `test/bgra04_copy_out_test.dart`'s independence/lifetime tests for the
/// contract this must not violate: the returned `Uint8List` must be an
/// independent copy, not a view, or the native buffer's `finally`-block free
/// immediately after copy-out would turn the result into a use-after-free
/// the next time that address is reused). Both candidates here are copies:
/// `Uint8List.fromList(...)` (A) and `.sublist(0)` on a `ByteBuffer`-backed
/// view (D) each allocate a fresh `Uint8List` and copy bytes into it -- the
/// intermediate `buffer.asUint8List(...)` in D is a *view*, but `.sublist(0)`
/// on it forces an immediate copy, never returned by itself. This file's own
/// per-sample independence check (mutate the native buffer right after
/// copying, assert the already-returned result is unaffected) re-verifies
/// this on-device for both candidates on every single sample, not just once
/// -- if either candidate ever returned a view, this would fail immediately
/// and loudly (wrong bytes at the next checksum), not silently. This
/// confirms D would be safe to adopt *if* it ever cleared the threshold --
/// it does not by itself argue for adopting it: per the task, no production
/// change is made in this card regardless of the numeric outcome below.
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  const warmup = 5;
  const samplesPerCandidate = 30;
  const width = 1920;
  const height = 1080;
  const rowStrideBytes = width * 4;
  const length = rowStrideBytes * height;
  const fnvBasis = 0xcbf29ce484222325;
  const fnvPrime = 0x100000001b3;
  const mask64 = 0xffffffffffffffff;
  const practicalThresholdPct = 5.0;

  int checksum(Uint8List plane) {
    var hash = fnvBasis;
    for (final value in plane) {
      hash = ((hash ^ value) * fnvPrime) & mask64;
    }
    return hash;
  }

  testWidgets('BGRA-04 Pixel 3 tight 1920x1080: interleaved A vs D copy-out, raw samples', (tester) async {
    final Pointer<Uint8> native = malloc<Uint8>(length);
    try {
      final Uint8List seed = Uint8List.fromList(List<int>.generate(length, (i) => (i * 41 + 7) & 255));
      native.asTypedList(length).setAll(0, seed);
      final int expectedHash = checksum(seed);

      Uint8List candidateA() => Uint8List.fromList(native.asTypedList(length));
      Uint8List candidateD() => (native.asTypedList(length).buffer.asUint8List(native.asTypedList(length).offsetInBytes, length)).sublist(0);

      // Warmup both candidates equally and outside the timed/randomized
      // sequence, so JIT/tiering effects do not bias whichever label happens
      // to be drawn first in the random order.
      for (var i = 0; i < warmup; i++) {
        candidateA();
        candidateD();
      }

      // Fixed seed, chosen once before running against hardware (see file
      // doc). Order is a Fisher-Yates shuffle of 30 'A' + 30 'D' tags.
      final random = Random(0xB6DA04);
      final order = <String>[...List.filled(samplesPerCandidate, 'A'), ...List.filled(samplesPerCandidate, 'D')];
      for (var i = order.length - 1; i > 0; i--) {
        final j = random.nextInt(i + 1);
        final tmp = order[i];
        order[i] = order[j];
        order[j] = tmp;
      }

      final rawSamplesUsA = <double>[];
      final rawSamplesUsD = <double>[];

      for (var idx = 0; idx < order.length; idx++) {
        final label = order[idx];
        final sw = Stopwatch()..start();
        final Uint8List result = label == 'A' ? candidateA() : candidateD();
        sw.stop();
        final us = sw.elapsedTicks * 1000000 / sw.frequency;

        final hash = checksum(result);
        expect(hash, expectedHash, reason: 'candidate $label: byte mismatch at sequence position $idx');

        // Per-sample independence/lifetime check (see file doc): mutate the
        // native buffer immediately after this copy and assert the already
        // -returned result is unaffected, for every single draw, not once.
        final int before = result[0];
        native.asTypedList(length)[0] = (native.asTypedList(length)[0] + 1) & 255;
        expect(result[0], before, reason: 'candidate $label: result changed after native buffer mutation at position $idx -- not independent');
        native.asTypedList(length)[0] = seed[0];

        (label == 'A' ? rawSamplesUsA : rawSamplesUsD).add(us);
      }

      double median(List<double> xs) {
        final sorted = xs.toList()..sort();
        return sorted[sorted.length ~/ 2];
      }

      final medianA = median(rawSamplesUsA);
      final medianD = median(rawSamplesUsD);
      final deltaUs = medianD - medianA;
      final deltaPct = (deltaUs / medianA) * 100;
      final dWinsByThreshold = deltaPct <= -practicalThresholdPct;

      debugPrint(
        jsonEncode({
          'card': 'BGRA-04',
          'device': 'pixel3',
          'experiment': 'interleaved_A_vs_D_tight_1080p',
          'scenario': 'tight-1920x1080',
          'length_bytes': length,
          'order_control': 'seeded_random_permutation',
          'seed': '0xB6DA04',
          'n_per_candidate': samplesPerCandidate,
          'median_ms_A': medianA / 1000,
          'median_ms_D': medianD / 1000,
          'min_ms_A': (rawSamplesUsA.toList()..sort()).first / 1000,
          'max_ms_A': (rawSamplesUsA.toList()..sort()).last / 1000,
          'min_ms_D': (rawSamplesUsD.toList()..sort()).first / 1000,
          'max_ms_D': (rawSamplesUsD.toList()..sort()).last / 1000,
          'delta_ms_D_minus_A': deltaUs / 1000,
          'delta_pct_D_vs_A': deltaPct,
          'practical_threshold_pct': practicalThresholdPct,
          'verdict': dWinsByThreshold ? 'D_WINS_ABOVE_THRESHOLD' : 'NO_DURABLE_WIN_BELOW_THRESHOLD',
          'checksum_fnv1a64': expectedHash,
          'device_state_note': 'Valid only if the device was Awake/screen-on/keyguard-dismissed for the whole run; see BGRA-00 review addendum.',
        }),
      );
      debugPrint(
        jsonEncode({
          'card': 'BGRA-04',
          'experiment': 'interleaved_A_vs_D_tight_1080p_raw',
          'raw_us_A': rawSamplesUsA,
          'raw_us_D': rawSamplesUsD,
          'raw_order': order.join(),
        }),
      );
    } finally {
      malloc.free(native);
    }
  });
}
