// ignore_for_file: avoid_web_libraries_in_flutter
//
// This file is the Web-only WASM bootstrap implementation and is imported
// through a conditional export (`wasm_loader.dart`), so web libraries here are
// intentional and isolated from non-web targets.
import 'dart:async';
import 'dart:html' as html;
import 'package:js/js_util.dart' as js_util;

/// Holds a reference to an initialized Emscripten module object.
///
/// We keep this wrapper intentionally thin at this stage:
/// - No YUV function bindings here yet (per current scope).
/// - Only loader/bootstrap concerns are implemented.
final class YuvModule {
  YuvModule(this.rawModule);

  /// Raw JS module object returned by `createYuvFfiModule(...)`.
  ///
  /// Future steps will map typed wrappers for exported functions and memory
  /// access (`_malloc`, `_free`, `HEAPU8`, etc.) on top of this object.
  final Object rawModule;
}

/// Loads and initializes the WebAssembly runtime for yuv_ffi on Web.
///
/// Current responsibilities:
/// 1. Inject the generated Emscripten JS loader script.
/// 2. Resolve and call global module factory (`createYuvFfiModule` by default).
/// 3. Cache initialization so repeated calls do not re-load/re-init.
///
/// Out of scope for this step:
/// - calling YUV processing exports,
/// - marshaling image planes to WASM memory.
final class YuvWasmLoader {
  const YuvWasmLoader._();

  /// Default package asset path for generated JS loader.
  ///
  /// For package assets in Flutter Web, `assets/packages/<package>/...` is the
  /// canonical runtime path.
  static const String defaultScriptPath = 'assets/packages/yuv_ffi/assets/wasm/yuv_ffi.js';

  /// Default package asset path for generated WASM binary.
  static const String defaultWasmPath = 'assets/packages/yuv_ffi/assets/wasm/yuv_ffi.wasm';

  /// Default global factory name generated by Emscripten when using:
  /// `-s MODULARIZE=1 -s EXPORT_NAME=createYuvFfiModule`.
  static const String defaultFactoryName = 'createYuvFfiModule';

  static Future<YuvModule>? _initFuture;
  static YuvModule? _module;

  /// Returns initialized module if available in current process, otherwise null.
  static YuvModule? get moduleIfInitialized => _module;

  /// Ensures the WASM runtime is initialized exactly once.
  ///
  /// Safe to call many times; all callers share the same in-flight/completed
  /// initialization future.
  static Future<YuvModule> ensureInitialized({
    String scriptPath = defaultScriptPath,
    String wasmPath = defaultWasmPath,
    String moduleFactoryName = defaultFactoryName,
  }) {
    return _initFuture ??= _initialize(
      scriptPath: scriptPath,
      wasmPath: wasmPath,
      moduleFactoryName: moduleFactoryName,
    );
  }

  static Future<YuvModule> _initialize({
    required String scriptPath,
    required String wasmPath,
    required String moduleFactoryName,
  }) async {
    await _injectScriptOnce(scriptPath);

    final factory = js_util.getProperty(
      js_util.globalThis,
      moduleFactoryName,
    );
    if (factory == null) {
      throw StateError(
        'WASM module factory "$moduleFactoryName" was not found on globalThis. '
        'Check that $scriptPath is built and loaded correctly.',
      );
    }

    // Emscripten accepts an options object. We set `locateFile` so runtime
    // always resolves the `.wasm` binary from our package asset path.
    final moduleConfig = js_util.newObject();
    js_util.setProperty(
      moduleConfig,
      'locateFile',
      js_util.allowInterop((String requestedName, Object? scriptDirectory) {
        if (requestedName.endsWith('.wasm')) {
          return wasmPath;
        }
        final prefix = scriptDirectory is String ? scriptDirectory : '';
        if (prefix.isNotEmpty) {
          return '$prefix$requestedName';
        }
        return requestedName;
      }),
    );

    final modulePromise = js_util.callMethod<Object>(
      factory,
      'call',
      <Object?>[null, moduleConfig],
    );

    final module = YuvModule(
      await js_util.promiseToFuture<Object>(modulePromise),
    );
    _module = module;
    return module;
  }

  static Future<void> _injectScriptOnce(String scriptPath) async {
    final existing = html.document.querySelector(
      'script[data-yuv-ffi-wasm-loader="1"]',
    );
    if (existing != null) {
      return;
    }

    final completer = Completer<void>();
    final script = html.ScriptElement()
      ..type = 'text/javascript'
      ..src = scriptPath
      ..async = true
      ..defer = true
      ..dataset['yuv-ffi-wasm-loader'] = '1';

    script.onLoad.listen((_) {
      if (!completer.isCompleted) {
        completer.complete();
      }
    });
    script.onError.listen((_) {
      if (!completer.isCompleted) {
        completer.completeError(
          StateError(
            'Failed to load WASM loader script: $scriptPath',
          ),
        );
      }
    });

    html.document.head?.append(script);
    await completer.future;
  }
}
