// ignore_for_file: avoid_web_libraries_in_flutter, deprecated_member_use
//
// This file is the Web-only WASM bootstrap implementation and is imported
// through a conditional export (`wasm_loader.dart`), so web libraries here are
// intentional and isolated from non-web targets.
import 'dart:async';
import 'dart:html' as html;
import 'dart:js_interop';

import 'package:yuv_ffi/src/web/impl/js_util_compat_web.dart' as js_util;

/// Holds a reference to an initialized Emscripten module object.
///
/// We keep this wrapper intentionally thin at this stage:
/// - No YUV function bindings here yet (per current scope).
/// - Only loader/bootstrap concerns are implemented.
final class YuvModule {
  YuvModule(this.rawModule);

  /// Raw JS module object returned by `createYuvFfiModule(...)`.
  ///
  /// Future steps will map typed wrappers for exported functions and memory
  /// access (`_malloc`, `_free`, `HEAPU8`, etc.) on top of this object.
  final Object rawModule;
}

/// Loads and initializes the WebAssembly runtime for yuv_ffi on Web.
///
/// Current responsibilities:
/// 1. Inject the generated Emscripten JS loader script.
/// 2. Resolve and call global module factory (`createYuvFfiModule` by default).
/// 3. Cache initialization so repeated calls do not re-load/re-init.
///
/// Out of scope for this step:
/// - calling YUV processing exports,
/// - marshaling image planes to WASM memory.
final class YuvWasmLoader {
  const YuvWasmLoader._();

  /// Default package asset path for generated JS loader.
  ///
  /// For package assets in Flutter Web, `assets/packages/<package>/...` is the
  /// canonical runtime path.
  static const String defaultScriptPath = 'assets/packages/yuv_ffi/assets/wasm/yuv_ffi.js';

  /// Default package asset path for generated WASM binary.
  static const String defaultWasmPath = 'assets/packages/yuv_ffi/assets/wasm/yuv_ffi.wasm';

  /// Default global factory name generated by Emscripten when using:
  /// `-s MODULARIZE=1 -s EXPORT_NAME=createYuvFfiModule`.
  static const String defaultFactoryName = 'createYuvFfiModule';

  static Future<YuvModule>? _initFuture;
  static YuvModule? _module;

  /// Number of times initialization actually started.
  ///
  /// A shared in-flight attempt counts once, which is what proves concurrent
  /// callers do not each start their own initialization.
  static int debugInitCount = 0;

  static Future<YuvModule> Function({
    required String scriptPath,
    required String wasmPath,
    required String moduleFactoryName,
  })? _initializerOverride;

  /// Replaces the initializer so tests can count attempts and fail
  /// deterministically without a real module. Not exported publicly.
  static void debugSetInitializer(
    Future<YuvModule> Function({
      required String scriptPath,
      required String wasmPath,
      required String moduleFactoryName,
    })? initializer,
  ) {
    _initializerOverride = initializer;
  }

  /// Drops every cached initialization handle and the counter together.
  static void debugReset() {
    _initializerOverride = null;
    _initFuture = null;
    _module = null;
    debugInitCount = 0;
  }

  /// Returns initialized module if available in current process, otherwise null.
  static YuvModule? get moduleIfInitialized => _module;

  /// Ensures the WASM runtime is initialized.
  ///
  /// Concurrent callers share one in-flight attempt, and a successful result is
  /// cached for the life of the process.
  ///
  /// A failed attempt is not cached: the future is cleared so the next explicit
  /// call starts a genuinely new attempt. On failure [moduleIfInitialized]
  /// stays `null`, so a partially initialized module is never observable.
  ///
  /// Unlike the native backend, Web has no lazy fallback: this must be awaited
  /// before any image operation. Configuration and runtime failures throw
  /// [StateError]; any other error propagates unchanged with its original stack
  /// trace.
  static Future<YuvModule> ensureInitialized({
    String scriptPath = defaultScriptPath,
    String wasmPath = defaultWasmPath,
    String moduleFactoryName = defaultFactoryName,
  }) {
    final inFlight = _initFuture;
    if (inFlight != null) {
      return inFlight;
    }

    debugInitCount++;
    final initializer = _initializerOverride ?? _initialize;
    late final Future<YuvModule> attempt;
    attempt = initializer(
      scriptPath: scriptPath,
      wasmPath: wasmPath,
      moduleFactoryName: moduleFactoryName,
    ).onError<Object>((error, stackTrace) {
      // Clear only if this attempt is still the current one. A later call may
      // already have replaced it, and dropping that newer future would make
      // concurrent callers wait on an attempt nobody owns any more.
      if (identical(_initFuture, attempt)) {
        _initFuture = null;
      }
      _module = null;
      Error.throwWithStackTrace(error, stackTrace);
    });
    _initFuture = attempt;
    return attempt;
  }

  static Future<YuvModule> _initialize({
    required String scriptPath,
    required String wasmPath,
    required String moduleFactoryName,
  }) async {
    await _injectScriptOnce(scriptPath);

    final factory = js_util.getProperty(
      js_util.globalThis,
      moduleFactoryName,
    );
    if (factory == null) {
      throw StateError(
        'WASM module factory "$moduleFactoryName" was not found on globalThis. '
        'Check that $scriptPath is built and loaded correctly.',
      );
    }

    // Emscripten accepts an options object. We set `locateFile` so runtime
    // always resolves the `.wasm` binary from our package asset path.
    final moduleConfig = js_util.newObject();
    String locateFile(JSString requestedName, JSAny? scriptDirectory) {
      final requestedNameDart = requestedName.toDart;
      if (requestedNameDart.endsWith('.wasm')) {
        return wasmPath;
      }
      final scriptDirectoryDart = scriptDirectory?.dartify();
      final prefix = scriptDirectoryDart is String ? scriptDirectoryDart : '';
      if (prefix.isNotEmpty) {
        return '$prefix$requestedNameDart';
      }
      return requestedNameDart;
    }

    js_util.setProperty(
      moduleConfig,
      'locateFile',
      locateFile.toJS,
    );

    final modulePromise = js_util.callMethod<Object>(
      factory,
      'call',
      <Object?>[null, moduleConfig],
    );

    final module = YuvModule(
      await js_util.promiseToFuture<Object>(modulePromise),
    );
    _module = module;
    return module;
  }

  /// Injects the Emscripten loader script, at most once per successful load.
  ///
  /// The marker attribute is what makes this idempotent, so a tag that failed to
  /// load has to be taken back out of the document. Leaving it there would make
  /// every later attempt find it, skip injection, and then fail looking for a
  /// factory that no script ever defined — a retry that reports the wrong cause
  /// and can never succeed. Only the error path removes it: a script that loaded
  /// is exactly what the marker is meant to record.
  ///
  /// Concurrent callers cannot race here: [ensureInitialized] coalesces them onto
  /// one in-flight attempt, so this runs alone.
  static Future<void> _injectScriptOnce(String scriptPath) async {
    final existing = html.document.querySelector(
      'script[data-yuv-ffi-wasm-loader="1"]',
    );
    if (existing != null) {
      return;
    }

    final completer = Completer<void>();
    final script = html.ScriptElement()
      ..type = 'text/javascript'
      ..src = scriptPath
      ..async = true
      ..defer = true
      ..dataset['yuv-ffi-wasm-loader'] = '1';

    script.onLoad.listen((_) {
      if (!completer.isCompleted) {
        completer.complete();
      }
    });
    script.onError.listen((_) {
      if (!completer.isCompleted) {
        // Drop the dead tag first, so the next attempt injects a fresh one.
        script.remove();
        completer.completeError(
          StateError(
            'Failed to load WASM loader script: $scriptPath',
          ),
        );
      }
    });

    html.document.head?.append(script);
    await completer.future;
  }
}
