name: CI Web

concurrency:
  group: ci-web-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/heads/release/') }}

on:
  push:
    branches:
      - "release/**"
      - main
    tags:
      - "ci/all/**"
      - "ci/web/**"
    paths-ignore: ["**/*.md", "doc/**", "tasks/**"]
  workflow_dispatch:

jobs:
  web:
    runs-on: [self-hosted, Windows, X64, web]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Web checks
        shell: pwsh
        run: ./tool/ci/web.ps1
