name: CI Web

concurrency:
  group: ci-web-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - "ci/all/**"
      - "ci/web/**"
  workflow_dispatch:

jobs:
  web:
    runs-on: [self-hosted, macOS, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Web checks
        shell: bash
        run: bash ./tool/ci/web.sh
